### PR TITLE
fix(complex): ignore traversals selector types

### PR DESCRIPTION
**Pull request by rdamlenc**
complex selectors should ignore [traversals selector types](https://github.com/fb55/css-what/blob/master/src/types.ts#L16) 

So `#foo .bar ul li a` complixity level would be `5` rather than `9`

### CODE REVIEW

**Review by macbre — APPROVED** [review]

**Comment by macbre** [comment]
Thanks for the fix.

> So #foo .bar ul li a complixity level would be 5 rather than 9

Can you add a test case for that, please?

**Comment by Jieiku** [comment]
Thanks for this fix, really looking forward to it :)

**Comment by Jieiku** [comment]
@rdamlenc is this ready to merge? I noticed @macbre mentioned adding a test case?

**Comment by macbre** [comment]
> @rdamlenc is this ready to merge? I noticed @macbre mentioned adding a test case?

I you can provide some selectors examples (with the expected complexity,), I'll be more than happy to add the test coverage here.

**Comment by Jieiku** [comment]
In my case analyze-css is used by yellowlabtools.

in the old version it reports as expected: https://yellowlab.tools/result/gtr25fqnyn/rule/cssComplexSelectors

but the new version being developed reports very differently: http://yellowlab.tools:8282/result/gtr26h6mbq/rule/cssComplexSelectors

You can see the list of detected selectors in the second link, but a couple from that list include:

```
footer nav a
main nav a
main nav span
```

and in more detail
```css
  footer nav {
    a {
        margin: .2rem;
    }
    i {
      margin-bottom: .2rem;
    }
  }

  main nav {
    margin-top: var(--s2);//pagination margin
    a,span {
      margin: .2rem;
    }
  }
```

both are the same site: https://abridge.netlify.app/

**Comment by macbre** [comment]
I've rebased this PR to merge into [c9d6af8](https://github.com/macbre/analyze-css/commit/c9d6af8411da1dcc8cc4a1b068890db4ef4d0ebc) that introduces some test cases.

**Pull request merged**
